
# tap repositories and their packages

tap 'homebrew/core'
brew 'aom'
brew 'aribb24'
brew 'brotli'
brew 'c-ares'
brew 'ca-certificates'
brew 'cairo'
brew 'cjson'
brew 'dav1d'
brew 'ffmpeg'
brew 'flac'
brew 'fontconfig'
brew 'freetype'
brew 'frei0r'
brew 'fribidi'
brew 'gdbm'
brew 'gettext'
brew 'gh'
brew 'giflib'
brew 'glib'
brew 'gmp'
brew 'gnutls'
brew 'gping'
brew 'graphite2'
brew 'harfbuzz'
brew 'highway'
brew 'icu4c'
brew 'imath'
brew 'jpeg-turbo'
brew 'jpeg-xl'
brew 'krb5'
brew 'lame'
brew 'leptonica'
brew 'libarchive'
brew 'libass'
brew 'libb2'
brew 'libbluray'
brew 'libevent'
brew 'libidn2'
brew 'libnghttp2'
brew 'libogg'
brew 'libpng'
brew 'librist'
brew 'libsamplerate'
brew 'libsndfile'
brew 'libsodium'
brew 'libsoxr'
brew 'libtasn1'
brew 'libtiff'
brew 'libunibreak'
brew 'libunistring'
brew 'libuv'
brew 'libvidstab'
brew 'libvmaf'
brew 'libvorbis'
brew 'libvpx'
brew 'libx11'
brew 'libxau'
brew 'libxcb'
brew 'libxdmcp'
brew 'libxext'
brew 'libxrender'
brew 'little-cms2'
brew 'lz4'
brew 'lzo'
brew 'macos-term-size'
brew 'mas'
brew 'mbedtls'
brew 'mpdecimal'
brew 'mpg123'
brew 'nettle'
brew 'node@14'
brew 'opencore-amr'
brew 'openexr'
brew 'openjpeg'
brew 'openssl@1.1'
brew 'openssl@3'
brew 'opus'
brew 'p11-kit'
brew 'pango'
brew 'pcre2'
brew 'pipx'
brew 'pixman'
brew 'postgresql@14'
brew 'python@3.10'
brew 'python@3.11'
brew 'rav1e'
brew 'readline'
brew 'rubberband'
brew 'sdl2'
brew 'snappy'
brew 'speex'
brew 'sqlite'
brew 'srt'
brew 'svt-av1'
brew 'tesseract'
brew 'theora'
brew 'unbound'
brew 'wakeonlan'
brew 'webp'
brew 'wget'
brew 'x264'
brew 'x265'
brew 'xorgproto'
brew 'xvid'
brew 'xz'
brew 'yarn'
brew 'zeromq'
brew 'zimg'
brew 'zstd'

tap 'homebrew/cask'
cask '1password'
cask 'arctype'
cask 'balenaetcher'
cask 'discord'
cask 'google-chrome'
cask 'iterm2'
cask 'miniforge'
cask 'ngrok'
cask 'pushplaylabs-sidekick'
cask 'raspberry-pi-imager'
cask 'raycast'
cask 'ultimaker-cura'
cask 'visual-studio-code'
cask 'vivaldi'

tap 'homebrew/bundle'

tap 'homebrew/services'

tap 'rcmdnk/file'
brew 'brew-file'

# App Store applications
mas 'Affinity Designer (1.10.6)', id: 824171161
mas 'DaVinci Resolve (18.1.4)', id: 571213070
mas 'Diffusers (1.1)', id: 1666309574
mas 'GoodNotes (5.9.91)', id: 1444383602
mas 'LINE (7.15.0)', id: 539883307
mas 'Microsoft Excel (16.70)', id: 462058435
mas 'Microsoft PowerPoint (16.70)', id: 462062816
mas 'Microsoft Word (16.70)', id: 462054704
mas 'OneDrive (23.038.0219)', id: 823766827
mas 'Slack (4.29.149)', id: 803453959
mas 'Tailscale (1.36.2)', id: 1475387142
