
# tap repositories and their packages

tap caskroom/cask
brew brew-cask
cask 1password
cask adobe-air
cask alfred
cask android-file-transfer
cask android-studio
cask appcleaner
cask applepi-baker
cask atom
cask bettertouchtool
cask blender
cask coteditor
cask couleurs
cask cyberduck
cask dash
cask disk-inventory-x
cask dropbox
cask evernote
cask gimp
cask google-chrome
cask google-japanese-ime
cask google-photos-backup
cask handbrake
cask handbrakecli
cask horndis
cask inkscape
cask iterm2
cask karabiner
cask keyboard-cleaner
cask kindle
cask librecad
cask libreoffice
cask loading
cask logitech-unifying
cask minecraft
cask music-manager
cask openscad
cask pandoc
cask parallels-desktop
cask scroll-reverser
cask seil
cask slack
cask sony-ericsson-bridge
cask sourcetree
cask timemachineeditor
cask tunnelbear
cask vagrant
cask vlc
cask wireshark
cask xld
cask xquartz

tap caskroom/versions
cask firefox-ja
cask java7
cask pycharm-ce
cask sublime-text-dev

tap homebrew/versions
brew docker141

tap rcmdnk/file
brew brew-file

tap sanemat/font

tap argon/mas
brew mas

# Other Homebrew packages
brew android-platform-tools
brew arp-scan
brew bash-completion
brew c-ares
brew cairo
brew czmq
brew d-bus
brew fontconfig
brew fontforge
brew fping
brew freetype
brew gdbm
brew geoip
brew gettext
brew glib
brew gmp
brew gnutls
brew go
brew gobject-introspection
brew harfbuzz
brew hping
brew httpie
brew httping
brew icu4c
brew iperf
brew jpeg
brew libffi
brew libgcrypt
brew libgpg-error
brew libpng
brew libsodium
brew libtasn1
brew libtiff
brew libtool
brew mackup
brew mobile-shell
brew nettle
brew nmap
brew noti
brew openssl
brew pandoc
brew pango
brew pixman
brew pkg-config
brew protobuf
brew python
brew python3
brew ssh-copy-id
brew wget
brew wireshark
brew zeromq
